version: '3.9'

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: students_db
    ports:
      - "5443:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  students_service:
    build:
      context: ./students
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://user:password@postgres_db:5443/students_db
      
  auth_service:
    build:
      context: ./auth
    ports:
      - "8002:8002"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://user:password@postgres_db:5443/students_db

  professions_service:
   build:
     context: ./professions
   ports:
     - "8001:8001"
   depends_on:
     - postgres_db
   environment:
     DATABASE_URL: postgresql://user:password@postgres_db/students_db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - students_service

volumes:
  postgres_db:
    driver: local
